pre-commit:
  enabled: true
  commands:
    format-java:
      name: "Format Java code"
      run: "mvn spotless:check"
    spotbugs-check:
      name: "SpotBugs static analysis"
      run: "mvn spotbugs:check"
    check-dependencies:
      name: "Check for dependency vulnerabilities"
      run: "mvn org.owasp:dependency-check-maven:check"

commit-msg:
  enabled: true
  commands:
    validate-commit-msg:
      name: "Validate commit message"
      run: "commitlint --edit {1}"

