services:
  app:
    build: ./
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - redis
    environment:
      BREVO_API: ${BREVO_API}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_SSL_ENABLED: ${REDIS_SSL_ENABLED}
      DB_SSL_ENABLED: ${DB_SSL_ENABLED}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      TELEGRAM_ENABLED: ${TELEGRAM_ENABLED}
      TELEGRAM_PATH: ${TELEGRAM_PATH}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_USERNAME: ${TELEGRAM_USERNAME}
      TELEGRAM_WEBHOOK_URL: ${TELEGRAM_WEBHOOK_URL}
      OPEN_AI_ASSISTANT: ${OPEN_AI_ASSISTANT}
      OPEN_AI_KEY: ${OPEN_AI_KEY}
      AVATAR_UPLOAD_DIR: ${AVATAR_UPLOAD_DIR}
      CHILD_PHOTO_UPLOAD_DIR: ${CHILD_PHOTO_UPLOAD_DIR}

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
    ports:
      - '5433:5432'
  redis:
    image: redis:latest
    container_name: redis-companion
    ports:
      - '6379:6379'